name: 'Check merge to master from dev as staging branch (on this repo)'

on:
  pull_request:
    branches:
    - master

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check HEAD pointer is from dev
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"
          THIS_REPO = "${{ github.repository }}"
          HEAD_REPO = "${{ github.event.pull_request.head.repo.full_name }}"

          echo "Check if allowed to merge $HEAD_REPO:$HEAD into $THIS_REPO:$BASE"
          
          if [[ "$BASE" == "master" && "HEAD_REPO" == "$THIS_REPO" && "$HEAD" != "dev" ]]; then
            echo "ERROR: Internal PRs to master must come from the dev branch."
            exit 1
          fi
          
          echo "OK, all good"
          exit 0
